version: '3.8'

services:

  workspace:
    build:
      context: ./php-fpm
      args:
        - PHP_VERSION=${PHP_VERSION}
    working_dir: /var/www/laravel
    volumes:
      - ../:/var/www/laravel
      - ./php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro
      - ./php-fpm/xphp.ini:/usr/local/etc/php/conf.d/xphp.ini:ro
    ports:
      - "${PHP_PORT}:9000"
      - "${VITE_PORT}:5173"
    tty: true
    networks:
      - laravel-network
    depends_on:
      mysql:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: ${NGINX_IMAGE}
    volumes:
      - ../:/var/www/laravel:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      #- ./nginx/error.log:/var/log/nginx/error.log
      #- ./nginx/access.log:/var/log/nginx/access.log
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - workspace
    networks:
      - laravel-network

  mysql:
    image: ${MYSQL_IMAGE}
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password']
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql/databases.sql:/docker-entrypoint-initdb.d/databases.sql:ro
      - mysql-data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - laravel-network
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 2s
      retries: 10

  mailpit:
    image: ${MAILPIT_IMAGE}
    ports:
      - "${MAILPIT_SMTP_PORT}:1025" # smtp server
      - "${MAILPIT_DASHBOARD_PORT}:8025" # web ui
    networks:
      - laravel-network


networks:
  laravel-network:
    driver: bridge

volumes:
  mysql-data:
